# Generated by Django 2.0.5 on 2019-07-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
